version: "3"
 
silent: true
 
vars:
  PYTHON_VERSION: '{{.PYTHON_VERSION | default "3.14"}}'
  VENV_NAME: ".venv"
 

tasks:
# --------------------------------------------------------------------------------------
# ENVIRONMENT
# --------------------------------------------------------------------------------------
  env:
    desc: Build virtual environment
    status:
      - test -d "{{.VENV_NAME}}"
    cmds:
      - uv venv {{.VENV_NAME}} --python {{.PYTHON_VERSION}}
 
 
  dev-env:
    desc: Create development environment
    status:
      - test -f {{.VENV_NAME}}/.env-type-dev
    deps: [env]
    cmds:
      - uv sync --group dev
      - uv run pre-commit install
      - echo "Dev environment ready."
 
 
# --------------------------------------------------------------------------------------
# DEVELOPMENT
# --------------------------------------------------------------------------------------
  lint:
    desc: Check code formatting without modifying files
    deps: [dev-env]
    cmds:
      - uv run isort --check-only src tests
      - uv run black --check src tests
 
 
  format:
    desc: Format the code
    deps: [dev-env]
    cmds:
      - uv run isort src tests
      - uv run black src tests
 
 
  test:
    desc: "Run tests. Options: VERBOSE=1, COV=1 (terminal only), COV_HTML=1 (terminal + html report)"    
    deps: [dev-env] 
    vars:
      PYTEST_FLAGS: >-
        {{if .VERBOSE}}-s --override-ini="addopts=-ra -p no:warnings"{{end}}
        {{if .COV}}--cov --cov-report=term-missing{{end}}
        {{if .COV_HTML}}--cov --cov-report=term-missing --cov-report=html{{end}}
    cmds:
      - uv run pytest {{.PYTEST_FLAGS}} {{.CLI_ARGS | default "tests"}}
 
 
# --------------------------------------------------------------------------------------
# CLEAN
# --------------------------------------------------------------------------------------
  clean:
    desc: Remove all artifacts created by the workflow
    cmds:
      - rm -rf {{.VENV_NAME}}
      - rm -f uv.lock
      - rm -rf .pytest_cache
      - rm -rf coverage-report
      - rm -f .coverage
      - echo "Cleaned."