name: CI


on:

  push:
    branches-ignore: [main]

  pull_request:
    branches: [main]


jobs:
# --------------------------------------------------------------------------------------
# Check code formatting
# --------------------------------------------------------------------------------------
  lint:
    name: Lint (Python ${{ matrix.python-version }})

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      # Setup CI environment
      - uses: actions/checkout@v6
      - uses: arduino/setup-task@v2
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      # Run tasks
      - run: task dev-env
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
      - run: task lint


# --------------------------------------------------------------------------------------
# Run unittests
# --------------------------------------------------------------------------------------
  test:
    name: Test (Python ${{ matrix.python-version }})

    if: github.event_name == 'pull_request'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]

    steps:
      # Setup CI environment
      - uses: actions/checkout@v6
      - uses: arduino/setup-task@v2
      - uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ matrix.python-version }}

      # Run tasks
      - run: task dev-env
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      - run: task test COV_HTML=1
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}

      # Upload coverage report as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-report-py${{ matrix.python-version }}
          path: coverage-report/
          retention-days: 7
